-- =============================================================
-- ADR Transport Pro 2026 — Supabase kurulum betiği (Faz 0b + 1)
-- Dashboard → SQL Editor → yapıştır → Run
-- Bu betik idempotenttir (tekrar çalıştırmak güvenlidir).
-- =============================================================

-- ── 1) İş tabloları (monolit şemasından çevrildi) ──
CREATE TABLE IF NOT EXISTS companies (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                type TEXT NOT NULL CHECK(type IN ('sender', 'receiver', 'carrier')),
                name TEXT NOT NULL,
                tax_number TEXT,
                tax_office TEXT,
                mersis_no TEXT,
                address TEXT,
                city TEXT,
                district TEXT,
                phone TEXT,
                email TEXT,
                contact_person TEXT,
                is_favorite INTEGER DEFAULT 0,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
                updated_at TEXT DEFAULT CURRENT_TIMESTAMP
            , logo_path TEXT DEFAULT '',
                tenant_id BIGINT NOT NULL DEFAULT 1
            );

CREATE TABLE IF NOT EXISTS drivers (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                full_name TEXT NOT NULL,
                tc_no TEXT UNIQUE,
                phone TEXT,
                adr_certificate_no TEXT,
                adr_certificate_expiry TEXT,
                src5_no TEXT,
                src5_expiry TEXT,
                license_class TEXT,
                license_expiry TEXT,
                is_active INTEGER DEFAULT 1,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
                updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
                tenant_id BIGINT NOT NULL DEFAULT 1
            );

CREATE TABLE IF NOT EXISTS vehicles (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                plate TEXT NOT NULL UNIQUE,
                trailer_plate TEXT,
                adr_compliance_cert_no TEXT,
                adr_compliance_expiry TEXT,
                inspection_date TEXT,
                inspection_expiry TEXT,
                tank_info TEXT,
                vehicle_type TEXT,
                max_capacity REAL DEFAULT 0,
                is_active INTEGER DEFAULT 1,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
                updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
                tenant_id BIGINT NOT NULL DEFAULT 1
            );

CREATE TABLE IF NOT EXISTS chemicals (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                un_number TEXT NOT NULL,
                classification_code TEXT DEFAULT '',
                proper_shipping_name_tr TEXT,
                proper_shipping_name_en TEXT,
                class_code TEXT,
                packing_group TEXT,
                tunnel_code TEXT,
                transport_category TEXT,
                segregation_group TEXT,
                special_provisions TEXT,
                lq_allowed INTEGER DEFAULT 0,
                eq_allowed INTEGER DEFAULT 0,
                limited_quantity TEXT DEFAULT '',
                excepted_quantity TEXT DEFAULT '',
                hazard_labels TEXT,
                tenant_id BIGINT NOT NULL DEFAULT 1
            );

CREATE TABLE IF NOT EXISTS shipments (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                document_no TEXT NOT NULL UNIQUE,
                document_date TEXT,
                status TEXT DEFAULT 'Taslak',
                sender_id INTEGER,
                receiver_id INTEGER,
                carrier_id INTEGER,
                driver_id INTEGER,
                vehicle_id INTEGER,
                total_points REAL DEFAULT 0,
                orange_plate_required INTEGER DEFAULT 0,
                written_instructions_required INTEGER DEFAULT 0,
                driver_adr_required INTEGER DEFAULT 0,
                tunnel_restriction_code TEXT,
                exemption_type TEXT DEFAULT 'Yok',
                is_validated INTEGER DEFAULT 0,
                validation_errors TEXT,
                notes TEXT,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
                updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
                created_by TEXT,
                tenant_id BIGINT NOT NULL DEFAULT 1
            );

CREATE TABLE IF NOT EXISTS shipment_items (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                shipment_id INTEGER NOT NULL,
                chemical_id INTEGER,
                un_number TEXT,
                proper_name TEXT,
                class_code TEXT,
                packing_group TEXT,
                packaging_type TEXT,
                packaging_count INTEGER DEFAULT 1,
                net_quantity REAL DEFAULT 0,
                gross_quantity REAL DEFAULT 0,
                unit TEXT DEFAULT 'kg',
                is_lq INTEGER DEFAULT 0,
                is_eq INTEGER DEFAULT 0,
                lq_max_per_package REAL DEFAULT 0,
                eq_max_per_package REAL DEFAULT 0,
                notes TEXT, tunnel_code TEXT DEFAULT '', transport_category TEXT DEFAULT '', segregation_group TEXT DEFAULT '', classification_code TEXT DEFAULT '',
                tenant_id BIGINT NOT NULL DEFAULT 1
            );

CREATE TABLE IF NOT EXISTS company_products (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                company_name TEXT NOT NULL DEFAULT '',
                trade_name TEXT NOT NULL,
                un_number TEXT NOT NULL,
                classification_code TEXT DEFAULT '',
                packing_group TEXT DEFAULT '',
                limited_quantity TEXT DEFAULT '',
                excepted_quantity TEXT DEFAULT '',
                transport_category TEXT DEFAULT '',
                tunnel_code TEXT DEFAULT '',
                special_provisions TEXT DEFAULT '',
                source_file TEXT DEFAULT '',
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(trade_name, un_number, classification_code)
            );

CREATE TABLE IF NOT EXISTS packaging_types (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code TEXT NOT NULL UNIQUE,
                name_tr TEXT,
                name_en TEXT,
                description TEXT,
                max_gross_mass REAL,
                un_tested INTEGER DEFAULT 0
            );

CREATE TABLE IF NOT EXISTS audit_logs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                timestamp TEXT DEFAULT CURRENT_TIMESTAMP,
                user_name TEXT,
                action TEXT,
                table_name TEXT,
                record_id INTEGER,
                old_values TEXT,
                new_values TEXT,
                ip_address TEXT
            );

CREATE TABLE IF NOT EXISTS settings (
                key TEXT PRIMARY KEY,
                value TEXT,
                description TEXT,
                tenant_id BIGINT NOT NULL DEFAULT 1
            );

-- ── 2) Kiracı kolonu varsayılanı + indeks + RLS ──
CREATE INDEX IF NOT EXISTS idx_companies_tenant ON companies(tenant_id);
ALTER TABLE companies ALTER COLUMN tenant_id SET DEFAULT COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1);
ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE companies FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_izolasyon ON companies;
CREATE POLICY tenant_izolasyon ON companies USING (tenant_id = COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1)) WITH CHECK (tenant_id = COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1));

CREATE INDEX IF NOT EXISTS idx_drivers_tenant ON drivers(tenant_id);
ALTER TABLE drivers ALTER COLUMN tenant_id SET DEFAULT COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1);
ALTER TABLE drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE drivers FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_izolasyon ON drivers;
CREATE POLICY tenant_izolasyon ON drivers USING (tenant_id = COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1)) WITH CHECK (tenant_id = COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1));

CREATE INDEX IF NOT EXISTS idx_vehicles_tenant ON vehicles(tenant_id);
ALTER TABLE vehicles ALTER COLUMN tenant_id SET DEFAULT COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1);
ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicles FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_izolasyon ON vehicles;
CREATE POLICY tenant_izolasyon ON vehicles USING (tenant_id = COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1)) WITH CHECK (tenant_id = COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1));

CREATE INDEX IF NOT EXISTS idx_chemicals_tenant ON chemicals(tenant_id);
ALTER TABLE chemicals ALTER COLUMN tenant_id SET DEFAULT COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1);
ALTER TABLE chemicals ENABLE ROW LEVEL SECURITY;
ALTER TABLE chemicals FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_izolasyon ON chemicals;
CREATE POLICY tenant_izolasyon ON chemicals USING (tenant_id = COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1)) WITH CHECK (tenant_id = COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1));

CREATE INDEX IF NOT EXISTS idx_shipments_tenant ON shipments(tenant_id);
ALTER TABLE shipments ALTER COLUMN tenant_id SET DEFAULT COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1);
ALTER TABLE shipments ENABLE ROW LEVEL SECURITY;
ALTER TABLE shipments FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_izolasyon ON shipments;
CREATE POLICY tenant_izolasyon ON shipments USING (tenant_id = COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1)) WITH CHECK (tenant_id = COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1));

CREATE INDEX IF NOT EXISTS idx_shipment_items_tenant ON shipment_items(tenant_id);
ALTER TABLE shipment_items ALTER COLUMN tenant_id SET DEFAULT COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1);
ALTER TABLE shipment_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE shipment_items FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_izolasyon ON shipment_items;
CREATE POLICY tenant_izolasyon ON shipment_items USING (tenant_id = COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1)) WITH CHECK (tenant_id = COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1));

CREATE INDEX IF NOT EXISTS idx_settings_tenant ON settings(tenant_id);
ALTER TABLE settings ALTER COLUMN tenant_id SET DEFAULT COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1);
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_izolasyon ON settings;
CREATE POLICY tenant_izolasyon ON settings USING (tenant_id = COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1)) WITH CHECK (tenant_id = COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::bigint, 1));

-- ── 3) Kimlik doğrulama tabloları (RLS dışı — bkz. webcore/auth.py) ──
CREATE TABLE IF NOT EXISTS tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact_email TEXT DEFAULT '',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS web_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    full_name TEXT DEFAULT '',
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user'
        CHECK (role IN ('admin', 'user', 'viewer')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    failed_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_web_users_tenant ON web_users(tenant_id);

-- ── 4) İlk kiracı + yönetici kullanıcı (görsel doğrulama için) ──
INSERT INTO tenants (name, contact_email)
SELECT 'SİAM TMGD Danışmanlık', 'info@siamtmgdk.com.tr'
WHERE NOT EXISTS (SELECT 1 FROM tenants WHERE name = 'SİAM TMGD Danışmanlık');

INSERT INTO web_users (tenant_id, username, full_name, password_hash, role)
SELECT t.id, 'umut', 'Umut', 'dc6089c22185d35383038177c9a2254c$2352cfd617e5466bab7f1f360649ae7312047d2422f359525d80b090e0d9801a', 'admin'
FROM tenants t WHERE t.name = 'SİAM TMGD Danışmanlık'
ON CONFLICT (username) DO NOTHING;

-- Örnek veri: Table Editor'de görebilmen için 1 kimyasal + 1 firma
SELECT set_config('app.tenant_id', (SELECT id::text FROM tenants WHERE name='SİAM TMGD Danışmanlık'), false);
INSERT INTO chemicals (un_number, proper_shipping_name_tr, class_code, packing_group, tunnel_code, transport_category)
SELECT '1203', 'BENZİN', '3', 'II', 'D/E', '2'
WHERE NOT EXISTS (SELECT 1 FROM chemicals WHERE un_number='1203');
INSERT INTO companies (type, name, city)
SELECT 'sender', 'ÖRNEK GÖNDEREN A.Ş.', 'İstanbul'
WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name='ÖRNEK GÖNDEREN A.Ş.');

-- Kurulum doğrulaması: aşağıdaki sorgu tablo ve kayıt sayılarını verir
SELECT 'tenants' AS tablo, count(*) FROM tenants
UNION ALL SELECT 'web_users', count(*) FROM web_users
UNION ALL SELECT 'chemicals', count(*) FROM chemicals
UNION ALL SELECT 'companies', count(*) FROM companies;