"""Masaüstü adr_database.db → PostgreSQL (Supabase) veri migrasyonu — Faz 6.

Kullanım:
    python araclar/migrate_desktop_to_pg.py \
        --sqlite /yol/adr_database.db \
        --dsn "postgresql://postgres.xxx:SIFRE@...pooler.supabase.com:6543/postgres" \
        --tenant 1 [--temizle]

Tasarım kararları:
  * ID'LER KORUNUR: sevkiyatlar sender_id/driver_id... ile firmalara bağlı;
    ID'ler değişirse ilişkiler kopar. Pg kolonları GENERATED BY DEFAULT
    olduğu için açık id ile ekleme serbesttir; ekleme sonrası her tablonun
    IDENTITY sayacı setval ile max(id)'ye sarılır (yoksa ilk yeni kayıt
    "duplicate key" ile çakışır).
  * KOLON KESİŞİMİ: yalnız iki tarafta da var olan kolonlar taşınır; şema
    farkları (örn. Pg'deki tenant_id) otomatik tolere edilir.
  * KİRACI: tüm satırlara --tenant değeri yazılır; bağlantı RLS oturumunu
    da aynı kiracıya kurar (WITH CHECK'ten geçer).
  * settings: anahtar bazlı upsert (mevcut ayarın üzerine yazar).
  * audit_logs: varsayılan olarak taşınır (--loglari-atla ile atlanabilir).
  * İDEMPOTENSLİK: --temizle verilirse hedefteki kiracı verisi önce silinir;
    verilmezse aynı id'li kayıt hedefte varsa satır atlanır (ON CONFLICT id).
"""

from __future__ import annotations

import argparse
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

# Bağımlılık sırası: önce referans verilenler
SIRA = ["companies", "drivers", "vehicles", "chemicals", "packaging_types",
        "company_products", "shipments", "shipment_items", "audit_logs"]
KIRACILI = {"companies", "drivers", "vehicles", "chemicals",
            "shipments", "shipment_items", "settings"}


def tasi(sqlite_yolu: str, dsn: str, tenant: int = 1,
         temizle: bool = False, loglari_atla: bool = False,
         log=print) -> dict:
    from webcore.pg import PgDatabaseManager

    kaynak = sqlite3.connect(sqlite_yolu)
    kaynak.row_factory = sqlite3.Row
    hedef = PgDatabaseManager(dsn, tenant_id=tenant)
    conn = hedef._get_conn()

    ozet = {}
    with conn.cursor() as cur:
        if temizle:
            for t in reversed(SIRA):
                cur.execute(f"DELETE FROM {t}")
            cur.execute("DELETE FROM settings")
            log(f"[temizle] kiracı {tenant} verisi silindi")

        for tablo in SIRA:
            if loglari_atla and tablo == "audit_logs":
                ozet[tablo] = "atlandı"
                continue
            try:
                satirlar = kaynak.execute(f"SELECT * FROM {tablo}").fetchall()
            except sqlite3.OperationalError:
                ozet[tablo] = "kaynakta yok"
                continue
            if not satirlar:
                ozet[tablo] = 0
                continue

            cur.execute(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_name = %s", (tablo,))
            pg_kolonlar = {r["column_name"] for r in cur.fetchall()}
            ortak = [k for k in satirlar[0].keys() if k in pg_kolonlar]

            eklenen = 0
            for r in satirlar:
                kolonlar = list(ortak)
                degerler = [r[k] for k in ortak]
                if tablo in KIRACILI and "tenant_id" in pg_kolonlar \
                        and "tenant_id" not in kolonlar:
                    kolonlar.append("tenant_id")
                    degerler.append(tenant)
                yertutucu = ", ".join(["%s"] * len(kolonlar))
                cur.execute(
                    f"INSERT INTO {tablo} ({', '.join(kolonlar)}) "
                    f"VALUES ({yertutucu}) ON CONFLICT (id) DO NOTHING",
                    degerler)
                eklenen += cur.rowcount
            ozet[tablo] = eklenen

            # IDENTITY sayacını ileri sar
            if "id" in pg_kolonlar:
                cur.execute(
                    f"SELECT setval(pg_get_serial_sequence('{tablo}', 'id'), "
                    f"GREATEST((SELECT COALESCE(MAX(id), 1) FROM {tablo}), 1))")
            log(f"[{tablo}] {eklenen}/{len(satirlar)} satır taşındı")

    # settings: anahtar bazlı upsert (id yok, PK=key)
    try:
        ayarlar = kaynak.execute("SELECT * FROM settings").fetchall()
        for r in ayarlar:
            hedef.set_setting(r["key"], r["value"],
                              r["description"] if "description" in r.keys() else "")
        ozet["settings"] = len(ayarlar)
        log(f"[settings] {len(ayarlar)} ayar upsert edildi")
    except sqlite3.OperationalError:
        ozet["settings"] = "kaynakta yok"

    kaynak.close()
    hedef.close()
    return ozet


def _dogrula(sqlite_yolu: str, dsn: str, tenant: int, log=print) -> bool:
    """Taşıma sonrası sayı ve örnek-ilişki doğrulaması."""
    from webcore.pg import PgDatabaseManager
    kaynak = sqlite3.connect(sqlite_yolu)
    hedef = PgDatabaseManager(dsn, tenant_id=tenant)
    tamam = True
    for t in SIRA + ["settings"]:
        try:
            kn = kaynak.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
        except sqlite3.OperationalError:
            continue
        hn = hedef.execute_one(f"SELECT COUNT(*) AS n FROM {t}")["n"]
        isaret = "✓" if hn >= kn else "✗"
        if hn < kn:
            tamam = False
        log(f"  {isaret} {t}: kaynak {kn} → hedef {hn}")
    # örnek ilişki: ilk sevkiyatın göndereni çözülüyor mu
    sev = hedef.execute_one(
        "SELECT s.id, c.name FROM shipments s "
        "JOIN companies c ON c.id = s.sender_id LIMIT 1")
    if sev:
        log(f"  ✓ ilişki örneği: sevkiyat #{sev['id']} → gönderen '{sev['name']}'")
    kaynak.close()
    hedef.close()
    return tamam


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--sqlite", required=True, help="masaüstü adr_database.db yolu")
    ap.add_argument("--dsn", required=True, help="PostgreSQL/Supabase bağlantı dizesi")
    ap.add_argument("--tenant", type=int, default=1)
    ap.add_argument("--temizle", action="store_true",
                    help="hedefteki kiracı verisini önce sil")
    ap.add_argument("--loglari-atla", action="store_true")
    a = ap.parse_args()

    print(f"Kaynak: {a.sqlite}\nHedef kiracı: {a.tenant}\n")
    ozet = tasi(a.sqlite, a.dsn, a.tenant, a.temizle, a.loglari_atla)
    print("\nÖzet:", ozet)
    print("\nDoğrulama:")
    ok = _dogrula(a.sqlite, a.dsn, a.tenant)
    print("\nSONUÇ:", "BAŞARILI ✓" if ok else "EKSİK VAR — yukarıdaki ✗ satırlarına bakın")
    sys.exit(0 if ok else 1)
