"""Web kimlik doğrulama katmanı — Faz 1.

Masaüstündeki lisans/makine-parmak-izi sistemi web'de anlamsızdır; yerine
klasik çok kiracılı kullanıcı modeli gelir:

    tenants   : müşteri firmalar (kiracılar)
    web_users : kullanıcılar (her biri bir kiracıya bağlı)

Bu iki tablo BİLİNÇLİ olarak RLS kapsamı DIŞINDADIR: giriş anında kiracı
henüz bilinmediği için kullanıcı kaydına kiracısız erişilebilmelidir.
Giriş doğrulanınca dönen tenant_id, PgDatabaseManager.set_tenant()'a
verilir ve o andan itibaren tüm veri RLS ile o kiracıya kilitlenir.

Parola: PBKDF2-HMAC-SHA256, 600.000 tur, kullanıcı başına rastgele tuz
(monolitteki _hash_password ile aynı aile; stdlib dışına bağımlılık yok).
"""

from __future__ import annotations

import hashlib
import hmac
import secrets
from typing import Optional

_ITERATIONS = 600_000


def hash_password(password: str, salt: Optional[bytes] = None) -> str:
    """'tuz$türetilmiş' biçiminde saklanabilir parola özeti üretir."""
    salt = salt or secrets.token_bytes(16)
    dk = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"),
                             salt, _ITERATIONS)
    return f"{salt.hex()}${dk.hex()}"


def verify_password(password: str, stored: str) -> bool:
    try:
        salt_hex, dk_hex = stored.split("$", 1)
    except ValueError:
        return False
    dk = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"),
                             bytes.fromhex(salt_hex), _ITERATIONS)
    return hmac.compare_digest(dk.hex(), dk_hex)


AUTH_SCHEMA = """
CREATE TABLE IF NOT EXISTS tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact_email TEXT DEFAULT '',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS web_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    full_name TEXT DEFAULT '',
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user'
        CHECK (role IN ('admin', 'user', 'viewer')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    failed_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_web_users_tenant ON web_users(tenant_id);
"""

_MAX_FAILED = 5          # ardışık hatalı giriş sınırı
_LOCK_MINUTES = 15       # kilit süresi (monolitteki kademeli kilitle uyumlu ruh)


class AuthManager:
    """Kiracı ve kullanıcı yönetimi + giriş doğrulama.

    db: PgDatabaseManager örneği (RLS'siz tablolarda da aynı bağlantı
    kullanılır; tenants/web_users politikasız olduğundan serbest erişilir).
    """

    def __init__(self, db):
        self.db = db
        self._ensure_schema()

    def _ensure_schema(self):
        conn = self.db._get_conn()
        with conn.cursor() as cur:
            cur.execute(AUTH_SCHEMA)

    # ── kiracı ───────────────────────────────────────────────────────
    def create_tenant(self, name: str, contact_email: str = "") -> int:
        return self.db.execute_insert(
            "INSERT INTO tenants (name, contact_email) VALUES (?, ?)",
            (name, contact_email))

    def get_tenants(self) -> list:
        return [dict(r) for r in self.db.execute(
            "SELECT * FROM tenants WHERE is_active ORDER BY name")]

    # ── kullanıcı ────────────────────────────────────────────────────
    def create_user(self, tenant_id: int, username: str, password: str,
                    full_name: str = "", role: str = "user") -> int:
        return self.db.execute_insert(
            "INSERT INTO web_users (tenant_id, username, password_hash, "
            "full_name, role) VALUES (?, ?, ?, ?, ?)",
            (tenant_id, username.strip().lower(),
             hash_password(password), full_name, role))

    def set_password(self, username: str, new_password: str) -> int:
        return self.db.execute_update(
            "UPDATE web_users SET password_hash = ?, failed_attempts = 0, "
            "locked_until = NULL WHERE username = ?",
            (hash_password(new_password), username.strip().lower()))

    # ── giriş ────────────────────────────────────────────────────────
    def login(self, username: str, password: str) -> Optional[dict]:
        """Başarıda kullanıcı sözlüğü döner (tenant_id dahil), aksi None.

        Başarısız denemeler sayılır; _MAX_FAILED aşılınca hesap
        _LOCK_MINUTES dakika kilitlenir (kaba kuvvet önlemi).
        """
        uname = username.strip().lower()
        row = self.db.execute_one(
            "SELECT * FROM web_users WHERE username = ? AND is_active",
            (uname,))
        if not row:
            return None

        locked = self.db.execute_one(
            "SELECT 1 AS kilitli FROM web_users "
            "WHERE username = ? AND locked_until IS NOT NULL "
            "AND locked_until > now()", (uname,))
        if locked:
            return None

        if not verify_password(password, row["password_hash"]):
            self.db.execute_update(
                "UPDATE web_users SET failed_attempts = failed_attempts + 1, "
                "locked_until = CASE WHEN failed_attempts + 1 >= ? "
                f"THEN now() + INTERVAL '{_LOCK_MINUTES} minutes' "
                "ELSE NULL END WHERE username = ?",
                (_MAX_FAILED, uname))
            return None

        self.db.execute_update(
            "UPDATE web_users SET failed_attempts = 0, locked_until = NULL "
            "WHERE username = ?", (uname,))
        user = dict(row)
        user.pop("password_hash", None)
        return user
